name: CI-CD-ML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    - name: Train model
      run: |
        python src/train.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: iris_model
        path: iris_model.joblib
