name: Scheduled Monitor Drift

on:
  schedule:
    - cron: '*/15 * * * *'  # A cada 15 minutos
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r templates/requirements.txt

      - name: Run Monitor Drift
        run: |
          python templates/src/monitor_drift.py
        env:
          S3_BUCKET: cd4ml-monitoring